source/includes/_stories.md.erb

ПР, на основе которых делалось описание:
- https://github.com/rees46/ios-sdk/pull/57
- https://github.com/rees46/ios-sdk/pull/69
Задача:
- https://github.com/rees46/planning/issues/107

docs(stories): swift sections stories text block descr

---

source/includes/_orders.md.erb

test(github-actions): test row in orders

---

source/includes/_stories.md.erb

ПР в основе описания:
- https://github.com/rees46/rees46-android-sdk/pull/8
Задача:
- https://github.com/rees46/planning/issues/108

docs(stories): java section, stories TextBlock description

---

source/includes/_notification_service.md.erb

Описание на основе этого ПР:
https://github.com/rees46/rees46-android-sdk/pull/17

docs(notification_service): android push description kotlin

---

source/includes/_profile.md.erb

Задача: https://github.com/rees46/planning/issues/723
Замена описания

docs(profile): change method description

---

source/includes/_search.md.erb

к этой задаче: https://github.com/rees46/planning/issues/55

docs(search): fashion_sizes parameter js

---

source/includes/_products.md.erb

к этой задаче: https://github.com/rees46/planning/issues/716

docs(products): get clients shopping cart

---

source/includes/_products.md.erb

к этой задаче: https://github.com/rees46/planning/issues/717

docs(products): get product from cart swift

---

source/includes/_tracking.md.erb

к этой задаче: https://github.com/rees46/planning/issues/426
по этому ПР : https://github.com/rees46/ios-sdk/pull/71

docs(tracking): full wish iOS description

---

source/includes/_tracking.md.erb

К этой задаче:
https://github.com/rees46/planning/issues/135

docs(tracking): full_wish examples

---

source/includes/_tracking.md.erb

К этой задаче:
- https://github.com/rees46/planning/issues/463

docs(tracking): custom order tracking js

---

source/includes/_tracking.md.erb

к этой задаче:
- https://github.com/rees46/planning/issues/466

docs(tracking): custom order tracking RN

---

source/includes/_search.md.erb

К этой задаче: 
- https://github.com/rees46/planning/issues/228

docs(search): fashion sizes example

---

source/includes/_products.md.erb

к этой задаче:
- https://github.com/rees46/planning/issues/582

docs(products): cart delete method update description

---

source/includes/_tracking.md.erb

К этой задаче:
- https://github.com/rees46/planning/issues/469

docs(tracking): custom orders support description

---

source/includes/_notifications.md.erb

к этой задаче:
- https://github.com/rees46/planning/issues/697

docs(notification): channel added

---

source/includes/_tracking.md.erb

Эта задача:
- https://github.com/rees46/planning/issues/913

docs(tracking): types added

---

source/includes/_categories.md.erb

К этой задаче:
- https://github.com/rees46/planning/issues/854

docs(categories): caching description

---

source/includes/_tracking.md.erb

к этой задаче:
- https://github.com/rees46/planning/issues/465

docs(tracking): tracking with custom properties iOS

---

source/includes/_products.md.erb

к этой задаче:
- https://github.com/rees46/planning/issues/715

docs(products): get clients cart js wrapper-method

---

source/includes/_stories.md.erb

исправления к задаче:
https://github.com/rees46/planning/issues/89

chore(stories): formatting fixed

---

source/includes/_products.md.erb

к этой задаче:
-https://github.com/rees46/planning/issues/716

chore(products): change variable

---

source/includes/_stories.md.erb
source/includes/_tracking.md.erb

к этой задаче:
- https://github.com/rees46/planning/issues/89

chore(stories):page refactor

---

source/includes/_init.md.erb

к этой задаче:
- https://github.com/rees46/planning/issues/283

docs(init): no cookies initialization

---

source/includes/_stories.md.erb

к этой задаче:
- https://github.com/rees46/planning/issues/825

docs(stories): stories on request description js

---

source/includes/_init.md.erb

к этой задаче: 
- https://github.com/rees46/planning/issues/283
@Nelfimov добавил

docs(init): cockieless mode description

---

source/includes/_stories.md.erb
source/index.html.md

https://github.com/rees46/planning/issues/954

docs(index,stories): change settings, remove text

---

source/includes/_stories.md.erb

https://github.com/rees46/planning/issues/827

docs(stories): story on request iOS

---

source/includes/_tracking.md.erb
source/includes/_triggers.md.erb

https://github.com/rees46/planning/issues/919
https://github.com/rees46/planning/issues/920

docs(triggers): triggers methods description

---

source/includes/_audience.md.erb
source/includes/_chats.md.erb
source/includes/_communications.md.erb
source/includes/_crm.md.erb
source/includes/_init.md.erb
source/includes/_intro.md.erb
source/includes/_mobile_push_tokens.md.erb
source/includes/_nps.md.erb
source/includes/_orders.md.erb
source/includes/_products.md.erb
source/includes/_profile.md.erb
source/includes/_recommendations.md.erb
source/includes/_reputation.md.erb
source/includes/_search.md.erb
source/includes/_segments.md.erb
source/includes/_sms.md.erb
source/includes/_stories.md.erb
source/includes/_subscriptions.md.erb
source/includes/_tracking.md.erb
source/includes/_transactionals.md.erb
source/includes/_triggers.md.erb
source/includes/_utilities.md.erb
source/index.html.md

к этой задаче:
- https://github.com/rees46/planning/issues/826

docs(stories): change stories on request description

---

source/includes/_stories.md.erb

https://github.com/rees46/planning/issues/827

docs(stories): configuration

---

source/includes/_init.md.erb

https://github.com/rees46/planning/issues/270

docs(init): autosending oush token flag initialization

---

source/includes/_recommendations.md.erb

https://github.com/rees46/planning/issues/762

docs(recommendations): request with location description

---

source/includes/_stories.md.erb

https://github.com/rees46/planning/issues/826

fix(stories): typo

---

source/includes/_audience.md.erb

https://github.com/rees46/planning/issues/980

docs(audience):parameter update

---

source/includes/_products.md.erb
source/includes/_recommendations.md.erb

https://github.com/rees46/planning/issues/959

docs(products): methods review

---

source/includes/_orders.md.erb

https://github.com/rees46/planning/issues/1047

docs(orders): parametes optionality notice added

---

source/includes/_recommendations.md.erb
source/includes/_search.md.erb
source/includes/_tracking.md.erb

https://github.com/rees46/planning/issues/1225

docs(includes): kotlin documentation updated

---

source/includes/_recommendations.md.erb

https://github.com/rees46/planning/issues/761

docs(recommendations): request example

---

source/includes/_products.md.erb

https://github.com/rees46/planning/issues/30

docs(products): back in stock subscription parameters

---

source/includes/_notification_service.md.erb

https://github.com/rees46/planning/issues/271

docs(notification_service): autopush tokens iOS description updated

---

source/includes/_mobile_push_tokens.md.erb

https://github.com/rees46/planning/issues/1337

docs(mobile_push-tokens): push notification kotlin description

---

source/includes/_tracking.md.erb

https://github.com/rees46/planning/issues/874

docs(tracking): message delivery traking iOS

---

source/includes/_tracking.md.erb

https://github.com/rees46/planning/issues/1375

docs(tracking): RN impementation descriptions changed

---

source/includes/_init.md.erb

https://github.com/rees46/planning/issues/1402

docs(init): versions description Android

---

source/includes/_stories.md.erb

https://github.com/rees46/planning/issues/1378

docs(stories): personalizatio module name change

---

source/includes/_triggers.md.erb

https://github.com/rees46/planning/issues/1313

docs(triggers): unsubscribe from price drop event iOS

---

source/includes/_init.md.erb

https://github.com/rees46/planning/issues/1360

docs(init): permission usage description RN

---

source/includes/_mobile_push_notifications.md.erb

https://github.com/rees46/planning/issues/300

docs(mobile_push_notifications): analytics label in push description

---

source/includes/_profile.md.erb

https://github.com/rees46/planning/issues/1435

docs(profile): profile supports any type of arrays ios description

---

source/includes/_products.md.erb

https://github.com/rees46/planning/issues/1404

docs(products): request with no parameters notice

---

source/includes/_mobile_push_notifications.md.erb

https://github.com/rees46/planning/issues/1493

docs(mobile_push_notifications): custom push android description

---

source/includes/_mobile_push_notifications.md.erb
source/includes/_tracking.md.erb

https://github.com/rees46/planning/issues/1715
</details>

docs(includes): code examples removed from the description section

---

source/includes/_search.md.erb

https://github.com/rees46/planning/issues/1702

docs(search): brand limit parameter description

---

source/includes/_init.md.erb

https://github.com/rees46/planning/issues/1724

docs(init): added dependencies description

---

source/includes/_init.md.erb

https://github.com/rees46/planning/issues/1667
</details>

docs(init): SPA mode for JS SDK description

---

source/includes/_stories.md.erb

https://github.com/rees46/planning/issues/1722
</details>

docs(stories): click listener description updated

---

source/includes/_stories.md.erb

https://github.com/rees46/planning/issues/1733
</details>

docs(stories): promocode copied message settings

---

source/includes/_init.md.erb

https://github.com/rees46/planning/issues/1753
</details>

docs(init): android SDK initialization description change

---

source/includes/_segments.md.erb

https://github.com/rees46/planning/issues/1748
<details><summary> Пруф</summary>
</details>

docs(segments): external id parameter in query description

---

source/includes/_init.md.erb

https://github.com/rees46/planning/issues/1815
</details>

docs(init): change description order

---

source/includes/_orders.md.erb

https://github.com/rees46/planning/issues/1835
</details>

docs(orders): new import orders fields

---

source/includes/_init.md.erb

https://github.com/rees46/planning/issues/1856
</details>

docs(init): cookieless value changed

---

source/includes/_promocodes.md.erb

https://github.com/rees46/planning/issues/1881
</details>

docs(promocodes): delete promocode method description

---

source/includes/_products.md.erb
source/includes/_search.md.erb

https://github.com/rees46/planning/issues/1865
</details>
Этот ПР не закрывает задачу. Будет дополнительное описание в руководстве маркетолога.

docs(includes): price margin filter description

---

source/includes/_search.md.erb

https://github.com/rees46/planning/issues/1903
</details>

docs(search): blank search RN support

---

source/includes/_products.md.erb

https://github.com/rees46/planning/issues/1904
</details>

docs(products): JS SDK listing

---

source/includes/_search.md.erb

https://github.com/rees46/planning/issues/1903
</details>

docs(search): example and the description changed

---

source/includes/_products.md.erb

https://github.com/rees46/development/issues/1940
</details>

docs(products): android sdk product listing

---

source/includes/_stories.md.erb

https://github.com/rees46/development/issues/1913
<details><summary> Пруф</summary>
</details>

docs(stories): oncklick listener description, optional functionality

---

source/includes/_products.md.erb

https://github.com/rees46/development/issues/2045
</details>

docs(products): get product info method kotlin description

---

source/includes/_search.md.erb

https://github.com/rees46/development/issues/1952
</details>

docs(search): scope search description, parameters tables

---

source/includes/_init.md.erb

https://github.com/rees46/development/issues/2139
</details>

docs(init): iOS swft initialization example

---

source/includes/_intro.md.erb

https://github.com/rees46/development/issues/1731

docs(intro): remove notice

---

source/includes/_recommendations.md.erb

https://github.com/rees46/development/issues/2216
<details>
<summary>Пруф</summary>
</details>

docs(recommendattions): with locations parameter description

---

source/includes/_init.md.erb

https://github.com/rees46/development/issues/2205
</details>

docs(init): iOS SDK initialization

---

source/includes/_init.md.erb

https://github.com/rees46/development/issues/2221
<details><summary>пруф</summary>
</details>

docs(init): notification parameters removed, tag description

---

source/includes/_products.md.erb

https://github.com/rees46/development/issues/2249
</details>

docs(products): android wrapper in products/cats method

---

source/includes/_profile.md.erb

https://github.com/rees46/development/issues/2293
</details>

docs(profile): custom profile properties support in android

---

source/includes/_profile.md.erb

https://github.com/rees46/development/issues/2310
</details>

docs(profile): user profile custom properties

---

source/includes/_mobile_in_app_push_notifications.md.erb
source/index.html.md

https://github.com/rees46/development/issues/2318
</details>

docs(source): in app mobile push notifications

---

source/includes/_products.md.erb
source/includes/_search.md.erb

https://github.com/rees46/development/issues/2396
<details><summary> Пруф</summary>
</details>
Этот ПР не закрывает задачу, также будет предупреждение в руководстве маркетолога.

docs(includes): search and listing limit warning

---

source/includes/_orders.md.erb

https://github.com/rees46/development/issues/2464
</details>

docs(orders): order structure update

---

source/includes/_search.md.erb

https://github.com/rees46/development/issues/2498
</details>

docs(search):rating parameter added

---

source/includes/_search.md.erb

https://github.com/rees46/development/issues/2526
</details>

docs(search): parameter name in description changed

---

source/includes/_profile.md.erb

https://github.com/rees46/development/issues/2559
</details>

docs(profile): public and private response description

---

source/includes/_search.md.erb

https://github.com/rees46/development/issues/2558
</details>

docs(search): excluded brands parameter in instant and full search

---

source/includes/_search.md.erb

https://github.com/rees46/development/issues/2600
</details>

docs(search): brand exclusion in search, android

---

source/includes/_search.md.erb

https://github.com/rees46/development/issues/2612
</details>

docs(search): exclude merchants in search for ios

---

source/includes/_init.md.erb

https://github.com/rees46/development/issues/2539
</details>

docs(init): seance description

---

source/includes/_stories.md.erb

https://github.com/rees46/development/issues/2642
</details>

docs(stories): stories api response with promocode

---

source/includes/_tracking.md.erb

https://github.com/rees46/development/issues/2703
</details>

docs(tracking): api response to the viewed event

---

source/includes/_audience.md.erb

https://github.com/rees46/development/issues/2772
</details>

docs(audience): id changed to external_id

---

source/includes/_init.md.erb

https://github.com/rees46/development/issues/2800
</details>

docs(init): parentViewController notice, comments in ios changed

---

source/includes/_profile.md.erb

https://github.com/rees46/development/issues/2819
</details>

docs(profile): profile set new properties

---

source/includes/_mobile_in_app_push_notifications.md.erb

https://github.com/rees46/development/issues/2883
</details>

docs(mobil-in-app-push-notifications): popup invocation examples android

---

source/includes/_profile.md.erb

https://github.com/rees46/development/issues/2909

feat: profile purge

---

source/includes/_product_collections.md.erb

https://github.com/rees46/development/issues/2901
</details>

docs(product-collections): query parameters, API response, notice

---

source/includes/_search.md.erb

https://github.com/rees46/development/issues/2354
</details>

docs(search): zero sum aggregation notice

---

source/includes/_product_collections.md.erb

https://github.com/rees46/development/issues/2901
</details>

docs(profuct-collections): changed curl adress

---

source/includes/_init.md.erb

https://github.com/rees46/development/issues/2938
</details>

docs(init): custom domain configuration in init JS SDK

---

source/includes/_product_collections.md.erb

https://github.com/rees46/development/issues/2901
</details>

docs(product-collection): html added to api response

---

source/includes/_init.md.erb

https://github.com/rees46/development/issues/2938
</details>

docs(init): change host name

---

source/includes/_init.md.erb

https://github.com/rees46/development/issues/2938
</details>

docs(init): changed hosts names

---

source/includes/_product_collections.md.erb

https://github.com/rees46/development/issues/2901
</details>

docs(product-collections): js sdk example

---

source/includes/_loyalty.cancel_event_bonus.md.erb

https://github.com/rees46/development/issues/3175

docs(_loyalty.cancel_event_bonus): changed url

---

source/includes/_products.md.erb

https://github.com/rees46/development/issues/3204
</details>

docs(products): query parameters descriptions updated

---

source/includes/_tracking.md.erb

https://github.com/rees46/development/issues/3246
</details>

docs(tracking): custom event tracking, payload parameter

---

source/includes/_profile.md.erb

https://t.me/c/2243138785/283/56809

docs(progile): example descriptions changed

---

source/includes/_init.md.erb

https://github.com/rees46/development/issues/3341
</details>
Этот ПР не закрывает задачу, также нужны изменения в руководство маркетолога.

docs(init): popup init description update

---

source/includes/_intro.md.erb

https://github.com/rees46/development/issues/3384
</details>

docs(intro): stream parameter explanation

---

source/includes/_notifications.md.erb
source/includes/_transactionals.md.erb

https://github.com/rees46/development/issues/3428
</details>

docs(includes): notifications method description

---

source/includes/_loyalty.checkout.apply.md.erb
source/includes/_loyalty.checkout.estimate.md.erb

feat: add bonuses amount to charge
